### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by kcotar** [langurmonkey/gaiasky#107]
I am working on the translation of this software and have some problems with the special characters (čžš) in our language as they are not displayed in the graphical interface. Theoretically this should not be a problem as everything is encoded in utf-8?

**Comment by langurmonkey** [comment]
Thanks for translating Gaia Sky to your language - what language is it?
Since the application is OpenGL based, font rendering is done using a pre-rendered texture atlas, which contains the necessary characters for the current languages. If you can send me a list of all the characters that need to be included (lower and upper case) I can regenerate the character textures so that they can be rendered.

**Comment by kcotar** [comment]
The language is Slovene and we need the following characters č ž š Č Ž Š. Do you need utf-8 codes or something else for those characters?

**Comment by langurmonkey** [comment]
I have re-generated the texture atlases with the new characters (see 1b25720e). Let me know if this works for you to close the issue.

**Comment by kcotar** [comment]
The characters are now rendered correctly, will push translation in few days.
