### ISSUE TITLE
Scripting interface: issues with setCameraPostion method

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#132]
Several things here:
1. The method name has a type (Postion instead of Position), which may surprise users. Could this be corrected (breaks existing code) or a second, otherwise identical method added? I'd like to have only the corrected version in the REST API, which people might enter manually.

2. The comment in `core/src/gaia/cu9/ari/gaiaorbit/script/IScriptingInterface.java` says that the camera position is in km, but it seems to be rather million km (checking when focusing the sun). 

3. When calling `setCameraPostion()` with double vector (3., 0., 0.), again focusing the sun, the GUI info panel (right bottom) shows "Dist 2.4739E6 km". What's the reason for the difference? Size of the object? The getDistanceTo("Sol") method also returns "2473896.0266113277".

4. Calling `setCamerPosition()` with double vector (0., 0., 0.), when focus is on the sun, the sun actually disappears. That's a bit odd, but being inside the object, I guess is not defined anyway, so this may need to be checked by the user code (script/REST).

**Comment by langurmonkey** [comment]
1. Fixed in incoming commit.
2. Fixed in incoming commit.
3. Yes, the object size, which in the case of stars is a bit fuzzy because we do not have an actual physical radius for most stars but still need to render them as models and need to know when to stop the camera. In the case of the sun it is around 6e5 Km
4. If you teleport inside an object the object is not rendered, obviously, as all the triangles face outwards. This case is usually enforced by restrictions on the camera movements and the geometry of close by objects, but the setCameraPosition() method does not check this, as the number of objects can be arbitrarily large.
