### ISSUE TITLE
Scripting interface: asynchronous mode?

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#133]
The scripting interface https://github.com/langurmonkey/gaiasky/blob/master/core/src/gaia/cu9/ari/gaiaorbit/script/IScriptingInterface.java source comment mentions a few times
> <strong>Warning: This method will only work in the asynchronous mode. 
> Run the script with the "asynchronous" check box activated!</strong>

What does this mean and how would I enable the asynchronous mode or ensure I have it enabled? The scripting GUI elements don't have that check box (anymore).

**Comment by langurmonkey** [comment]
The sycnrhonous mode is no longer exposed. The ability to run scripts in a synchronous manner is implemented though, see [here](https://github.com/langurmonkey/gaiasky/blob/master/desktop/src/gaia/cu9/ari/gaiaorbit/script/JythonFactory.java#L93). Basically, what changes is that if ``async`` is on, the script is run in its own thread. Otherwise, the script is run inline in the main thread.
This is just a warning indicating that the function will probably cause problems if the script that calls it is run synchronously.
