### ISSUE TITLE
Incorrect size of "Sol" via scripting interface

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#174]
When querying the radius of objects with the scripting interface, I obtain the radius in km. However, for the sun the value is quite off (468156 km instead of ~ 696000 km). I guess stars are treated differently from planets (which have their sizes defined in the json files)...
```
from time import sleep
from gaia.cu9.ari.gaiaorbit.script import EventScriptingInterface
gs = EventScriptingInterface.instance()
gs.disableInput()
gs.cameraStop()

name = "Sol"
rad = gs.getObjectRadius(name)
text = "%s has a radius of %f km." % (name, rad)
gs.displayMessageObject(1, text, 0.5, 0.5, 1.0, 0.7, 0.0, 1.0, 38)
sleep(3)
gs.removeObject(1)
gs.enableInput()
```

**Comment by langurmonkey** [comment]
Yes, stars do not have a proper physical size, even though we derive a size from the magnitude to be used internally by the render system. The getRadius() applies a factor to convert to that internal size to the physical size and that should be normalized so that the getRadius() of the Sun yields the correct info. I will investigate this.
