### ISSUE TITLE
Adding meshes

### ISSUE THREAD

**Issue by kevinjardine** [langurmonkey/gaiasky#205]
This is more a question than an issue. I would like to add a 30% isosurface mesh. I notice that the meshes have a "separated" suffix. Is there a processing step before I convert the obj file to g3db?

**Comment by langurmonkey** [comment]
Yes, and the reason behind it is rather technical. Since libgdx uses signed short indices, the maximum number of vertices/faces is 2^15. That number is rather low by today's standards, but it ensures compatibility with OpenGL ES. Each model is composed by a set of parts, and that restriction only applies within each part, so what I do is split the model into different parts in blender using a connectivity operator and if any of the parts exceeds the number of vertices or faces, apply a decimate operator to reduce the count.

**Comment by kevinjardine** [comment]
OK thanks. Gives me an excuse to learn more Blender features.
