### ISSUE TITLE
Feature request: galactic cartesian coordinates

### ISSUE THREAD

**Issue by kevinjardine** [langurmonkey/gaiasky#211]
It would be nice to be able to set the position of the camera in a galactic cartesian coordinate system. Earth at (0,0,0), positive x-axis pointing to galactic centre, positive z axis pointing to north galactic pole. Values in parsecs.

Or at least a utility function to convert galactic cartesian coordinates to the ones used by the setCameraPosition function in the scripting package.

**Comment by kevinjardine** [comment]
Part of the problem is that when I convert (l,b) = (0,90) to (ra,dec) using these equations:

https://gist.github.com/barentsen/2367839

convert these values to cartesian coordinates:

r = 1000
x = r*cos(ra) * cos(dec)
y = r*sin(ra) * cos(dec)
z = r*sin(dec)

and then run this:

pcTokm = 3.086e13
p = [x*pcTokm, y*pcTokm, z*pcTokm]
gs.setCameraPosition(p)

then I do not get a view looking down from the north galactic pole as I expected.

A utility function to do the conversion would be helpful.

**Comment by langurmonkey** [comment]
That's because the internal ref sys is not a right-hand (XY equatorial plane and Z pointing to pole) as you would expect. Can you try:
```
p = [z*pcToKm, -x*pcToKm, y*pcToKm]
```
Also, you need to convert from galactic cartesian to equatorial cartesian (internal refsys is equatorial). To do so, you can build up your own transformation matrix in your script or use the one given in [the Coordinates class](https://github.com/langurmonkey/gaiasky/blob/master/core/src/gaia/cu9/ari/gaiaorbit/util/coord/Coordinates.java), with [`galacticToEquatorial()`](https://github.com/langurmonkey/gaiasky/blob/master/core/src/gaia/cu9/ari/gaiaorbit/util/coord/Coordinates.java#L200). But this returns a Matrix4d, which can only operate with Vector3d instances, very cumbersome, so I will add some helper functions in the scripting API to transform coordinates from spherical galactic, ecliptic and equatorial to the internal reference system.

**Comment by kevinjardine** [comment]
Thank you!

**Comment by kevinjardine** [comment]
For now I can hack this by going to TYC 1995-2504-1, which has b = 89.8 and then looking at the Earth.

**Comment by kevinjardine** [comment]
I had a better idea. I added this line at the top of mwsc.dat:

NGP,192.859479,27.12825,1500,0,0,,0.1,5

Now I can just go to NGP (north galactic pole) as a good place for a face-on galactic plane view.

**Comment by langurmonkey** [comment]
That's a nice, clever workaround ;)

**Comment by langurmonkey** [comment]
Just commited the new API calls, feel free to try them out (see 5893f08).

**Comment by kevinjardine** [comment]
OK, will do. I hope to use them to do more animations like this one:

https://www.youtube.com/watch?v=TCaxlP6sk5Y

(Although in future perhaps with music and a voice commentary.)

**Comment by langurmonkey** [comment]
Woa, that looks great! Keep me posted if you produce more.
