### ISSUE TITLE
Add-ons

### ISSUE THREAD

**Issue by RED29** [langurmonkey/gaiasky#250]
Maybe I missing something, but is it possible to add add-ons or more database sources?

**Comment by langurmonkey** [comment]
Yes, add-ons are possible, but there are none available yet. 
As for database sources, yes, Gaia Sky has a very flexible loading mechanism which makes it very easy to load different kinds of data from different types of files. More on that can be found in the [documentation](http://gaia-sky.readthedocs.io/en/latest/Data-catalogs-formats.html).

**Comment by RED29** [comment]
Ok, thanks for the quick reply! Love to read the documentation about the features... 
I want also to give the compliment for this great space simulator software. It is far more better than others I have tried. I hope that the community will grow! Is there also a donation address for supporting this great software?

**Comment by langurmonkey** [comment]
Sorry about the docs, but at this stage there is no way around it, specially for loading new catalogs. I would suggest using the [STIL loader](http://gaia-sky.readthedocs.io/en/latest/Data-catalogs-formats.html#stil-data-provider), as it accepts VOTable, FITS, CSV, etc. You can also use SAMP to get data in Gaia Sky from Topcat or Aladin since a few commits ago, so there's that.

Also, thanks for the offering, but there is no way to donate to the project.

**Comment by langurmonkey** [comment]
Can I close the issue?

**Comment by RED29** [comment]
Ok clear answer. I will look into the STIL loader. For now you can close this specific issue. Thanks!
