### ISSUE TITLE
Problem loading many asteroid orbits

### ISSUE THREAD

**Issue by mommermi** [langurmonkey/gaiasky#98]
I tried to generate orbits for all known asteroids and read them, but gaiasky fails to load with the following output:

```
...
14:10:56: Orbit data loaded: 2016 UF112 (501 points)
14:10:56: Orbit data loaded: 2016 UX116 (501 points)
14:10:56: Orbit data loaded: 2016 VU4 (501 points)
14:10:56: Orbit data loaded: data/orb.MERCURY.dat (102 points)
14:10:56: Orbit data loaded: data/orb.VENUS.dat (123 points)
14:10:56: Orbit data loaded: data/orb.EARTH.dat (199 points)
14:10:56: Orbit data loaded: data/orb.MARS.dat (373 points)
14:10:56: Orbit data loaded: data/orb.JUPITER.dat (988 points)
14:10:56: Orbit data loaded: data/orb.SATURN.dat (985 points)
14:10:56: Orbit data loaded: data/orb.URANUS.dat (979 points)
14:10:56: Orbit data loaded: data/orb.NEPTUNE.dat (982 points)
14:10:56: Orbit data loaded: data/orb.MOON.dat (102 points)
14:10:56: Orbit data loaded: Phobos orbit (181 points)
14:10:56: Orbit data loaded: Deimos orbit (235 points)
14:10:56: Orbit data loaded: Amalthea orbit (501 points)
14:10:56: Orbit data loaded: Io orbit (501 points)
14:10:56: Orbit data loaded: Europa orbit (501 points)
14:10:56: Orbit data loaded: Ganymede orbit (501 points)
14:10:56: Orbit data loaded: Callisto orbit (501 points)
14:10:56: Orbit data loaded: Prometheus orbit (501 points)
14:10:56: Orbit data loaded: Vesta orbit (501 points)
14:10:56: Orbit data loaded: Ceres orbit (501 points)
14:10:56: Orbit data loaded: Pallas orbit (501 points)
14:10:56: Orbit data loaded: Hygieia orbit (501 points)
14:10:56: Orbit data loaded: data/orb.GAIA.dat (6,248 points)
14:10:56: PointDataProvider - 57,332 objects loaded from file data/galaxy/galaxy_40000particles.txt
14:10:56: PointDataProvider - 80 objects loaded from file data/galaxy/galaxy_80particles.txt
14:10:56: SceneGraph - Inserting 9,559 nodes into the scene graph...
14:10:57: Constellation - Constellations stars not found (HIP): 10826
14:10:57: Constellation - Constellations stars not found (HIP): 10826
14:10:57: Constellation - Constellations stars not found (HIP): 90968
14:10:57: Constellation - Constellations stars not found (HIP): 97629
14:10:57: Constellation - Constellations stars not found (HIP): 97629
14:10:57: SceneGraph - Scene graph initialised with 9,559 objects
14:10:57: Initialising renderer and GUI
14:11:00: SceneGraphRenderer - Max texture size: 8192^2 pixels
14:11:01: SceneGraphRenderer - Depth buffer size: 24 bits
14:11:02: Initialising GUI
14:11:02: Initialising SG tree
14:11:02: SG tree initialised
14:11:02: Camera focus changed to Earth
Controllers: added manager for application, 1 managers active
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: Java heap space
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at gaia.cu9.ari.gaiaorbit.render.system.LineQuadRenderSystem.initVertices(LineQuadRenderSystem.java:84)
	at gaia.cu9.ari.gaiaorbit.render.system.LineQuadRenderSystem.addLineInternal(LineQuadRenderSystem.java:151)
	at gaia.cu9.ari.gaiaorbit.render.system.LineQuadRenderSystem.addLineInternal(LineQuadRenderSystem.java:116)
	at gaia.cu9.ari.gaiaorbit.render.system.LineQuadRenderSystem.addLine(LineQuadRenderSystem.java:112)
	at gaia.cu9.ari.gaiaorbit.scenegraph.Orbit.render(Orbit.java:145)
	at gaia.cu9.ari.gaiaorbit.scenegraph.LineObject.render(LineObject.java:10)
	at gaia.cu9.ari.gaiaorbit.render.system.LineQuadRenderSystem.renderStud(LineQuadRenderSystem.java:210)
	at gaia.cu9.ari.gaiaorbit.render.system.AbstractRenderSystem.render(AbstractRenderSystem.java:46)
	at gaia.cu9.ari.gaiaorbit.render.SceneGraphRenderer.renderScene(SceneGraphRenderer.java:401)
	at gaia.cu9.ari.gaiaorbit.render.SGR.render(SGR.java:29)
	at gaia.cu9.ari.gaiaorbit.render.SceneGraphRenderer.render(SceneGraphRenderer.java:374)
	at gaia.cu9.ari.gaiaorbit.GaiaSky.renderSgr(GaiaSky.java:501)
	at gaia.cu9.ari.gaiaorbit.GaiaSky.render(GaiaSky.java:432)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

Reading in 700 asteroids works just fine, but it starts failing with 7000 asteroids, or more. I uploaded the file that fails [here](https://github.com/mommermi/mommermi.github.io/blob/master/gaiasky/asteroids.json?raw=true).

**Comment by langurmonkey** [comment]
Definitely an out of memory problem. Since each asteroid gets its own model object this might not be the best approach to get them into Gaia Sky.
However, I did a quick test:

1.  Increasing the max heap memory to 4 GB [here](https://github.com/ari-zah/gaiasky/blob/master/desktop/exe/gaiasky#L35) (or in the [windows launcher](https://github.com/ari-zah/gaiasky/blob/master/desktop/exe/gaiasky.bat#L5) or in the [gradle build file](https://github.com/ari-zah/gaiasky/blob/master/desktop/build.gradle#L31) depending on what you use to launch the app). 
2.  Relaxing a bit the number of samples per orbit [here](https://github.com/ari-zah/gaiasky/blob/master/core/src/gaia/cu9/ari/gaiaorbit/data/orbit/OrbitalParametersProvider.java#L31) — it actually depends on the length of the semi-major axis; the maximum number of samples was 500 per orbit, I reduced it to 200. 
3.  Choosing HYG instead of TGAS in the data tab to have more room for the asteroid orbits.

With these I could load all the orbits —see attached images— even though it kills the frame rate (I get about 1 FPS in a very old 8800 GTS). Probably decreasing the number of samples even further and using a decent graphics card would be enough to get interactive rates. I will need to do some testing.

About the orientation, I will investigate further. Probably a simple extra parameter in the orbit file will suffice.

![20161123_screenshot_00000](https://cloud.githubusercontent.com/assets/1049893/20563517/3f87acdc-b189-11e6-905c-e811a9506dfd.jpg)
![20161123_screenshot_00001](https://cloud.githubusercontent.com/assets/1049893/20563522/43c9796a-b189-11e6-813d-b34899261787.jpg)
![20161123_screenshot_00002](https://cloud.githubusercontent.com/assets/1049893/20563524/45db3b1c-b189-11e6-82df-9475e2cbb2c6.jpg)

**Comment by langurmonkey** [comment]
Some more news.
I toned down the colors a bit, used simple `GL_LINES` instead of the shaded quads mode (halves the number of vertices) and reduced the number of samples. The thing is now running at interactive rates (about 15 FPS with `glc-capture` on). 

The lines don't look very good though because they overlap at different distances so it is impossible to sort them for proper alpha blend rendering unless we split them into parts, which would kill performance.
See this [unlisted Youtube video](https://www.youtube.com/watch?v=7i5V0ub-2DE). Sorry for the quality. Youtube encoding is horrible. Also, data cluttering is strong with this one.

**Comment by langurmonkey** [comment]
As for the reference plane being Earth's equator instead of the ecliptic plane, the solution is already in place, as I suspected. We just need to add a new parameter `"transformFunction": "equatorialToEcliptic"` to the definition.

#### Example
```json
{
    "name": "60 Echo",
    "parent": "Sol",
    "color": [
        0.5,
        1.0,
        0.5,
        0.8
    ],
    "orbit": {
        "epoch": 2457800.5,
        "meananomaly": 355.66724,
        "semimajoraxis": 357962687.0586,
        "eccentricity": 0.1832334,
        "argofpericenter": 270.99363,
        "ascendingnode": 191.59609,
        "period": 0.27411194928064958,
        "inclination": 3.60148
    },
    "provider": "gaia.cu9.ari.gaiaorbit.data.orbit.OrbitalParametersProvider",
    "impl": "gaia.cu9.ari.gaiaorbit.scenegraph.Orbit",
    "ct": "Orbits",
    "transformFunction": "equatorialToEcliptic"
}
```

**Comment by langurmonkey** [comment]
Also, with commit 3bed8b8aace3b9c0d6c2f8628f42d44538f5f548 we can now have more than one visibility type (`ComponentType`) per object, so that asteroid orbits are only shown when both Asteroids and Orbits are active.

#### Example

```json
{
    "name": "60 Echo",
    "parent": "Sol",
    "color": [
        0.5,
        1.0,
        0.5,
        0.8
    ],
    "orbit": {
        "epoch": 2457800.5,
        "meananomaly": 355.66724,
        "semimajoraxis": 357962687.0586,
        "eccentricity": 0.1832334,
        "argofpericenter": 270.99363,
        "ascendingnode": 191.59609,
        "period": 0.27411194928064958,
        "inclination": 3.60148
    },
    "provider": "gaia.cu9.ari.gaiaorbit.data.orbit.OrbitalParametersProvider",
    "impl": "gaia.cu9.ari.gaiaorbit.scenegraph.Orbit",
    "ct": [ "Orbits", "Asteroids" ],
    "transformFunction": "equatorialToEcliptic"
}
```

**Comment by langurmonkey** [comment]
Finally closing this. Commit fe97f02abaa283f0cc2421941b392f87258d9a5c introduced a new orbit mode, VBO lines, which basically send all the line points to the GPU to do the work. This results in a boost in performance (20 vs 60 FPS with a GTX1070 for about 700 orbits). The full 7000 data file yields between 10 and 30 FPS  with the new method depending on how many line segments are in view.
